version: "3.8"  # Specify the version of Docker Compose

services:
  app:
    build:
      context: .  # Path to the Dockerfile
    ports:
      - "8080:8080"  # Expose port 8080 on the host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      REDIS_HOST: localhost  # Hostname of the Redis service
      REDIS_PORT: 6379   # Redis default port
      REDIS_PASSWORD: SUPER_SECRET_PASSWORD
    depends_on:
      - db  # Ensure the database starts before the app
      - redis  # Ensure Redis starts before the app

  db:
    image: postgres:15-alpine  # Use the PostgreSQL image
    container_name: my_postgres
    ports:
      - "5432:5432"  # Expose port 5432 on the host
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

  redis:
    image: redis:alpine  # Use the lightweight Redis image
    container_name: my_redis
    ports:
      - "6379:6379"  # Expose port 6379 on the host
    command: ["redis-server", "--appendonly", "yes"]  # Enable persistent storage
    volumes:
      - redis_data:/data  # Persist Redis data

volumes:
  postgres_data:  # Define a named volume for the database
  redis_data:  # Define a named volume for Redis
